### ISSUE TITLE
As a developer I want  a  modular file structure, so that I can quickly and easily understand the breakdown of this React App.

### ISSUE THREAD

**Issue by ashton-huxtable** [shayan-golafshani/rancid-tomatillos#15]
---------------------------------------------

Add modular file structure to components folders

like so  \/
---------------------------------------------
src
|_components
  |_App
    |_App.js
    |_App.css
  |_Form
    |_Form.js
    |_Form.csss
  |_OtherComponent
etc

**Comment by shayan-golafshani** [comment]
- [x] Created folders
- [x] Create matching CSS and JS files
- [x] Make sure imports match up to use properly
