### ISSUE TITLE
As a user I should be able to see the details of the movie I selected on the home page, so I can see if I want to watch it or not.

### ISSUE THREAD

**Issue by ashton-huxtable** [shayan-golafshani/rancid-tomatillos#4]
Utilize conditional rendering to display just a single movie rather than all movies 
Ensure that the condition works if this.state.currentMovie is empty or has a movie in it

**Comment by shayan-golafshani** [comment]
- [x] Use conditional rendering to display a single movie.
 - [x] Set up conditional rendering so this happens
 - [x] Ensure that the condition works if this.state.currentMovie is empty or has a movie in it
