### ISSUE TITLE
As a user, I should be able to return home by clicking a return home button, after viewing a movie's details 

### ISSUE THREAD

**Issue by ashton-huxtable** [shayan-golafshani/rancid-tomatillos#5]
After displaying a single movie, add a button to return home
Add functionality to display all movies again

**Comment by shayan-golafshani** [comment]
- [x]  Add a button to return home on the movie details page
- [x] Add an onClick to the button
- [x]  Pass in a function  that can be invoked on the onClick to return the user back to the home page view
- [x] Add functionality to re-display all movies again from the App.js render function
